"""Generate the switcher's config (~/llama-swap/config.yaml) from the control panel registry.

The same registry always renders byte-identical text, so a save that changes nothing writes
nothing and llama-swap does not reload. Every model entry starts with a marker line; the panel
uses the markers to compare entries and to keep ("hold") a loaded model's old entry when Jay
chooses "next time" (llama-swap patch P5 keeps a loaded model only while its entry is unchanged).

A new file is written to config.yaml.new, checked with ``llama-swap --config <new>
--check-config`` (patch P5), and only then swapped in with os.replace. A failed check leaves
the old file in place and raises SwitcherRefused with the switcher's own reason.

Strings are written as JSON strings, which are valid YAML double-quoted scalars, so names with
quotes, colons or # parse back unchanged. Command words with characters outside a safe set are
single-quoted for llama-swap's POSIX splitting; ${...} macros inside quotes still expand.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import stat
import re
import shlex
import shutil
import subprocess
import sys
import urllib.parse
from pathlib import Path
from typing import Any, Callable, Mapping

from . import ninfer_dials
from .registry import effective_settings, idle_minutes, write_atomic

HEADER = "# generated by the control panel from registry.json; edits here are overwritten"
MARKER = "  # --- model {id} ---"
_MARKER_RE = re.compile(r"^  # --- model (?P<id>[a-z0-9][a-z0-9._-]*) ---$")
_REPO = "${env.HOME}/FreeToken/engines"
MACROS = (
    ("ft", f"{_REPO}/adapters/freetoken.sh"),
    ("ninfer", f"{_REPO}/adapters/ninfer.sh {_REPO}/ninfer/build/apps/ninfer-serve"),
    ("ninfer_upstream", f"{_REPO}/adapters/ninfer.sh {_REPO}/ninfer-upstream/build/apps/ninfer-serve"),
)
RUNTIME_MACRO = {"ninfer": "ninfer", "ninfer-upstream": "ninfer_upstream"}
NINFER_HOST, NINFER_PORT = "127.0.0.1", 8090
NINFER_ENV = ["PATH=/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin"]
PROXY = {"freetoken": "http://127.0.0.1:2020", "ninfer": "http://127.0.0.1:8090"}
UNLOAD_TIMEOUT = {"freetoken": 180, "ninfer": 60}
_SAFE_WORD = re.compile(r"^[A-Za-z0-9_./:=@%+,${}-]+$")
_MACRO = re.compile(r"\$\{([A-Za-z0-9_.-]+)\}")


class SwitcherRefused(RuntimeError):
    """The switcher's --check-config refused a generated config."""


def default_config_path() -> Path:
    return Path(os.environ.get("FREETOKEN_SWAP_CONFIG") or Path.home() / "llama-swap" / "config.yaml")


def default_binary() -> Path:
    return Path(os.environ.get("FREETOKEN_LLAMA_SWAP_BIN")
                or Path.home() / ".local" / "share" / "freetoken-engines" / "bin" / "llama-swap")


def _q(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _num(value: Any) -> str:
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _word(text: str) -> str:
    return text if _SAFE_WORD.match(text) else shlex.quote(text)


def profile_id(model_id: str) -> str:
    return f"model-{model_id}"


def config_path(path: str) -> str:
    """~/x -> ${env.HOME}/x, so the file works for whichever user runs the switcher."""
    if path == "~":
        return "${env.HOME}"
    if path.startswith("~/"):
        return "${env.HOME}/" + path[2:]
    return path


def model_cmd(doc: Mapping[str, Any], model: Mapping[str, Any]) -> str:
    artifact = _word(config_path(model["artifact"]))
    if model["engine"] == "freetoken":
        return f"${{ft}} --profile {profile_id(model['id'])} {artifact}"
    flags = ninfer_dials.render_flags(effective_settings(doc, model), model["runtime"], path=config_path)
    words = [f"${{{RUNTIME_MACRO[model['runtime']]}}}", artifact, model["id"],
             "--host", NINFER_HOST, "--port", str(NINFER_PORT), *(_word(flag) for flag in flags)]
    return " ".join(words)


def model_block(doc: Mapping[str, Any], model: Mapping[str, Any]) -> str:
    engine = model["engine"]
    lines = [
        MARKER.format(id=model["id"]),
        f"  {_q(model['id'])}:",
        f"    name: {_q(model['name'])}",
        f"    cmd: {_q(model_cmd(doc, model))}",
        f"    proxy: {_q(PROXY[engine])}",
    ]
    if engine == "freetoken":
        folder = os.path.basename(model["artifact"].rstrip("/"))
        lines.append(f"    checkEndpoint: {_q('/ready?model=' + urllib.parse.quote(folder, safe=''))}")
    else:
        lines.append(f"    checkEndpoint: {_q('/health')}")
        lines.append(f"    useModelName: {_q(model['id'])}")
    lines += [
        f"    unloadTimeout: {UNLOAD_TIMEOUT[engine]}",
        f"    ramNeedGB: {_num(model['ramNeedGB'])}",
        f"    ttl: {idle_minutes(doc, model) * 60}",
        f"    aliases: {_q(list(model.get('aliases') or []))}",
    ]
    if engine == "ninfer":
        lines.append(f"    env: {_q(NINFER_ENV)}")
        lines.append("    filters:")
        lines.append(f"      clampParams: {_q(ninfer_dials.clamp_params())}")
    return "\n".join(lines) + "\n"


def render_config(doc: Mapping[str, Any], holds: Mapping[str, str] | None = None) -> str:
    holds = holds or {}
    system = doc["system"]
    lines = [
        HEADER, "",
        "healthCheckTimeout: 600", "logLevel: info", "sendLoadingState: false", "globalTTL: 0", "",
        "memoryGate:", "  probe: windows", f"  floorGB: {_num(system['floorGB'])}",
        f"  waitSeconds: {int(system['waitSeconds'])}", f"  helperURL: {_q(system['helperURL'])}", "",
        "routing:", "  scheduler:", "    settings:", "      fifo:",
        f"        latestWins: {'true' if system['latestWins'] else 'false'}", "",
        "macros:", *(f"  {name}: {_q(value)}" for name, value in MACROS), "",
        "models:",
    ]
    text = "\n".join(lines) + "\n"
    for model in doc["models"]:
        text += holds.get(model["id"]) or model_block(doc, model)
    return text


def extract_model_blocks(text: str | None) -> dict[str, str]:
    if not text or not text.startswith(HEADER + "\n"):
        return {}
    blocks: dict[str, str] = {}
    current: str | None = None
    buffer: list[str] = []
    for line in text.splitlines(keepends=True):
        match = _MARKER_RE.match(line.rstrip("\n"))
        if match:
            if current is not None:
                blocks[current] = "".join(buffer)
            current, buffer = match.group("id"), [line]
        elif current is not None:
            buffer.append(line)
    if current is not None:
        blocks[current] = "".join(buffer)
    return blocks


def config_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---- reading configs back (import and the live comparison) ----

def expand_macros(text: str, macros: Mapping[str, str], env: Mapping[str, str]) -> str:
    def one(match: re.Match[str]) -> str:
        name = match.group(1)
        if name in macros:
            return macros[name]
        if name.startswith("env."):
            return env.get(name[4:], "")
        return match.group(0)

    for _ in range(10):
        expanded = _MACRO.sub(one, text)
        if expanded == text:
            break
        text = expanded
    return text


def runtime_of(path: str) -> str:
    if "/engines/ninfer-upstream/" in path:
        return "ninfer-upstream"
    if "/engines/ninfer/" in path:
        return "ninfer"
    raise ValueError(f"unknown NInfer runtime {path}")


def describe_launch(args: list[str]) -> dict[str, Any]:
    script = os.path.basename(args[0]) if args else ""
    if script == "freetoken.sh":
        rest, profile = list(args[1:]), None
        if rest[:1] == ["--profile"] and len(rest) >= 2:
            profile, rest = rest[1], rest[2:]
        return {"engine": "freetoken", "folder": rest[0].rstrip("/") if rest else "", "profile": profile}
    if script == "ninfer.sh" and len(args) >= 4:
        settings, fixed = ninfer_dials.parse_flags(list(args[4:]))
        return {"engine": "ninfer", "runtime": runtime_of(args[1]), "artifact": args[2], "modelId": args[3],
                "host": fixed.get("--host"), "port": fixed.get("--port"),
                "settings": ninfer_dials.normalized(settings)}
    raise ValueError(f"unknown adapter {args[0] if args else '(empty command)'}")


def semantic_models(text: str, env: Mapping[str, str] | None = None) -> dict[str, dict[str, Any]]:
    import yaml

    env = dict(os.environ if env is None else env)
    doc = yaml.safe_load(text) or {}
    macros = {str(key): str(value) for key, value in (doc.get("macros") or {}).items()}
    out: dict[str, dict[str, Any]] = {}
    for model_id, entry in (doc.get("models") or {}).items():
        entry = entry or {}
        clamp = ((entry.get("filters") or {}).get("clampParams") or {})
        out[str(model_id)] = {
            "name": entry.get("name"),
            "launch": describe_launch(shlex.split(expand_macros(str(entry.get("cmd") or ""), macros, env))),
            "proxy": entry.get("proxy"),
            "checkEndpoint": entry.get("checkEndpoint", "/health"),
            "useModelName": entry.get("useModelName", ""),
            "unloadTimeout": entry.get("unloadTimeout"),
            "ramNeedGB": float(entry.get("ramNeedGB", 0) or 0),
            "ttl": int(entry.get("ttl", 0) or 0),
            "aliases": list(entry.get("aliases") or []),
            "env": list(entry.get("env") or []),
            "clampParams": {str(k): [float(x) for x in v] for k, v in clamp.items()},
        }
    return out


def compare(old_text: str, new_text: str, env: Mapping[str, str] | None = None) -> list[str]:
    """Differences that change behaviour. The FreeToken --profile word is expected and ignored."""
    old, new = semantic_models(old_text, env), semantic_models(new_text, env)
    diffs: list[str] = []
    for model_id in sorted(set(old) | set(new)):
        if model_id not in new:
            diffs.append(f"{model_id}: only in the old config")
            continue
        if model_id not in old:
            diffs.append(f"{model_id}: only in the new config")
            continue
        for key in sorted(set(old[model_id]) | set(new[model_id])):
            left, right = old[model_id].get(key), new[model_id].get(key)
            if key == "launch":
                left = {k: v for k, v in left.items() if k != "profile"}
                right = {k: v for k, v in right.items() if k != "profile"}
            if left != right:
                diffs.append(f"{model_id}.{key}: {left!r} -> {right!r}")
    return diffs


# ---- the safe writer ----

class SwapConfigWriter:
    def __init__(self, path: str | os.PathLike[str] | None = None, *, binary: str | os.PathLike[str] | None = None,
                 runner: Callable[..., Any] = subprocess.run, timeout: float = 30.0) -> None:
        self.path = Path(path) if path is not None else default_config_path()
        self.binary = Path(binary) if binary is not None else default_binary()
        self._runner = runner
        self.timeout = timeout

    def current_text(self) -> str | None:
        try:
            return self.path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return None

    def check(self, text: str) -> Path:
        """Stage ``text`` as config.yaml.new and have the switcher check it. Keeps the staged file.

        The .new file appears whole or not at all (temporary file, fsync, os.replace): a disk
        that filled part-way used to leave a partial .new behind (stage A deferred minor)."""
        staged = self.path.with_name(self.path.name + ".new")
        self.path.parent.mkdir(parents=True, exist_ok=True)
        try:
            write_atomic(staged, text.encode("utf-8"), 0o644)
        except BaseException:
            staged.unlink(missing_ok=True)
            raise
        try:
            ok, message = self._run_check(staged)
        except BaseException:
            staged.unlink(missing_ok=True)
            raise
        if not ok:
            staged.unlink(missing_ok=True)
            raise SwitcherRefused(message)
        return staged

    def _run_check(self, staged: Path) -> tuple[bool, str]:
        if not self.binary.is_file():
            return False, f"the switcher program was not found at {self.binary}; build it with scripts/engines/build.sh"
        try:
            proc = self._runner([str(self.binary), "--config", str(staged), "--check-config"],
                                capture_output=True, text=True, timeout=self.timeout, check=False)
        except subprocess.TimeoutExpired:
            return False, "the switcher's config check did not finish in time"
        output = ((proc.stdout or "") + (proc.stderr or "")).strip()
        last = output.splitlines()[-1] if output else f"exit code {proc.returncode}"
        return proc.returncode == 0, last

    def commit(self, staged: Path) -> None:
        """Swap the staged file in. A hand-written file is copied by the caller BEFORE anything
        else changes (backup_hand_written): done here, a copy that could not be made failed
        after the registry was already saved (PR #20 review)."""
        os.replace(staged, self.path)

    def backup_hand_written(self) -> Path | None:
        """Copy a config the control panel did not write (no generated header) to
        config.yaml.hand-<time> before it is replaced. Restore, import and the start-up sync
        all replace the whole file, and a hand-written one was lost with no copy (stage A
        deferred minor); import's one-off .bak-before-registry only covered the first time."""
        text = self.current_text()
        if not (text or "").strip() or text.startswith(HEADER + "\n"):
            return None
        stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
        target = self.path.with_name(f"{self.path.name}.hand-{stamp}")
        # Keep the source's permissions, never wider than 0600-by-default: a hand-written
        # config may carry llama-swap apiKeys (PR #20 review round 2).
        try:
            mode = stat.S_IMODE(self.path.stat().st_mode) & 0o600
        except OSError:
            mode = 0o600
        write_atomic(target, text.encode("utf-8"), mode or 0o600)
        return target

    def discard(self, staged: Path) -> None:
        Path(staged).unlink(missing_ok=True)

    def write(self, text: str) -> bool:
        if self.current_text() == text:
            return False
        staged = self.check(text)
        try:
            self.backup_hand_written()
        except BaseException:
            self.discard(staged)
            raise
        self.commit(staged)
        return True

    def backup_before_registry(self) -> Path | None:
        target = self.path.with_name(self.path.name + ".bak-before-registry")
        if not self.path.exists() or target.exists():
            return None
        shutil.copy2(self.path, target)
        return target


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) == 3 and args[0] == "compare":
        old = Path(args[1]).read_text(encoding="utf-8")
        new = Path(args[2]).read_text(encoding="utf-8")
        diffs = compare(old, new)
        print("\n".join(diffs) if diffs else "same: every model launches and routes the same way")
        return 1 if diffs else 0
    print("usage: python -m freetoken.daemon.settings.swap_config compare OLD.yaml NEW.yaml", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
